### PR TITLE
Add support for parent selector extensions (`&-foo`).

### PR DESCRIPTION
**Pull request by amannn**
This fixes the first issue described in #15 .

Was great fun to implement this, using functional programming techniques for traversing ASTs is a great fit 👍 .

### CODE REVIEW

**Comment by atfzl** [comment]
Thanks for the PR. 👍 

I'll review this over the weekend.

**Comment by amannn** [comment]
Thanks, much appreciated! I just ran this on a codebase of 14,6k LOC with quite a few parent selectors and it works for all relevant use cases :)

After a cleanup with this plugin, I was able to get rid of quite a few unused classes and removed invalid class references in markup. To be honest I was a little bit surprised that there were so many. Very valuable plugin 👍

**Comment by amannn** [comment]
I renamed the PR to `Add support for parent selector extensions` as it actually doesn't introduce support for parent selectors in general, but rather for parent selector extensions – which is something more specific.

**Comment by amannn** [comment]
Thanks for merging! I've added PR #21 that adds the tests for errors.

**Pull request merged**
